/**
 This constants class stores global values for cross-logic use, following our standardized format for clarity and consistency.
 */
public class TKE_CommonConstants {
     public static final String ID_FIELD = 'Id';
     public static final String AMPM_FORMAT = 'M/d/yyyy, h:mm a';
     public static final String CATEGORY_TIMEZONECONVERSION = 'Timezone Conversions';
     public static final String TIMEZONE_NEWYORK = 'America/New_York';
     public static final String ARRIVALWINDOW_STARTTIME = 'ArrivalWindowStartTime';
     public static final String ARRIVALWINDOW_ENDTIME = 'ArrivalWindowEndTime';
}